hlpr\install_wim_tweak.exe /p %mnt% /r /n /c LanguageFeatures-WordBreaking
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-OneCore-CHSIME
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-OneCore-Edge-WebRuntime
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-OneCore-IME
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-OneCore-Maps
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-OneCore-SpeechComponents
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-OneCore-Update-OrchestratorSchedulerTasks
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-OneCore-Update-OrchestratorScheduler-UXTasks
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-OneCore-Upfc
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-OneCore-WaaSAssessment
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-OneCore-WaaSMedic
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-BLB
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-DiagnosticInfrastructure
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-IME
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-InternetExplorer-Optional
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-LanguageFeatures
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-MediaPlayer
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-msmq
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-MSMQ
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-MSPaint
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-NetFx-Shared-WCF
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-NetFx3-WCF
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-NetFx4-WCF
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-OfflineFiles
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-PowerShell-ISE
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-Printing-XpsDocumentWriter
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-Printing-XPSServices
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-SenseClient
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-ShellSync
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-SnippingTool
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-StepsRecorder
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-TabletPCMath
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-WindowsMediaPlayer-Troubleshooters
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-WinSATMediaFiles
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-WMPNetworkSharingService
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-WordPad
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Windows-Xps-Xps-Viewer
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Windows-Defender
hlpr\install_wim_tweak.exe /p %mnt% /r /n /c Microsoft-Server-AzureArcSetup
exit /b